baseURL = "https://Hugo6991.github.io/Gu-Stack"
languageCode = "zh-CN"
title = "WebStack网址导航 Hugo主题"
theme = "webstack-hugo"
preservetaxonomynames = true
disablepathtolower = true
hascjklanguage = true
copyright = ""
[params]
  author = "iplaycode"
  description = "webstack hugo"
[params.search]
  enable = false
[params.darkmode]
  enable = false